// Where to stay. Five areas around Villa Apparita, ~27 places we picked out
// ourselves.
//
// Facts are stored as data (minutes, room counts, amenity keys) and the
// bilingual prose is generated by the formatters at the bottom — writing
// "5 Min. mit dem Auto" / "5 min by car" by hand 27 times is how this file
// would rot. Only the blurbs are hand-written, and only once per place.

import type { L } from './i18n';

const bi = (en: string, de: string): L => ({ en, de });

/* ---------------------------------------------------------------- vocabulary */

export type Amenity =
	| 'pool'
	| 'breakfast'
	| 'kitchen'
	| 'restaurant'
	| 'garden'
	| 'walkable'
	| 'selfCatering'
	| 'animals'
	| 'view';

export const amenityLabel: Record<Amenity, L> = {
	pool: bi('Pool', 'Pool'),
	breakfast: bi('Breakfast', 'Frühstück'),
	kitchen: bi('Kitchen', 'Küche'),
	restaurant: bi('Restaurant', 'Restaurant'),
	garden: bi('Garden', 'Garten'),
	walkable: bi('Walk to the villa', 'Zu Fuß zur Villa'),
	selfCatering: bi('Self-catering', 'Selbstverpflegung'),
	animals: bi('Animals', 'Tiere'),
	view: bi('View', 'Aussicht'),
};

export type RoomKind = 'double' | 'family' | 'apartment' | 'room' | 'wholeHouse' | 'villa';

// German plurals often equal the singular, so both forms are stored rather
// than derived with a suffix rule.
export const roomLabel: Record<RoomKind, { one: L; many: L }> = {
	double: { one: bi('double room', 'Doppelzimmer'), many: bi('double rooms', 'Doppelzimmer') },
	family: { one: bi('family room', 'Familienzimmer'), many: bi('family rooms', 'Familienzimmer') },
	apartment: { one: bi('apartment', 'Ferienwohnung'), many: bi('apartments', 'Ferienwohnungen') },
	room: { one: bi('room', 'Zimmer'), many: bi('rooms', 'Zimmer') },
	wholeHouse: { one: bi('the whole house', 'das ganze Haus'), many: bi('houses', 'Häuser') },
	villa: { one: bi('villa', 'Villa'), many: bi('villas', 'Villen') },
};

// Small labels that belong to the fields above rather than to page prose, so
// they live here and not in copy.ts.
export const stayVocab = {
	reserved: bi('Held for our guests', 'Für unsere Gäste reserviert'),
	askUs: bi('Ask us', 'Fragt uns'),
};

/* -------------------------------------------------------------------- types */

export type RoomSpec = { kind: RoomKind; count?: number };
export type Distance = { minutes: number; km?: number; mode?: 'car' | 'foot' };

export type Stay = {
	/** Proper noun — never translated, rendered without `<Bi>`. */
	name: string;
	blurb: L;
	/** Omit to inherit the group's distance. */
	distance?: Distance;
	rooms?: RoomSpec[];
	sleeps?: number;
	amenities?: Amenity[];
	url?: string;
	email?: string;
	phone?: string;
	/** No booking route of its own — we broker it. */
	askUs?: boolean;
	/** Rooms already reserved for our guests. */
	reserved?: boolean;
	/** Free-form caveat, e.g. a minimum stay. */
	caveat?: L;
};

export type StayGroup = {
	/** Anchor target — `#stay-monticchiello`. */
	id: string;
	name: L;
	tagline: L;
	/** Default for the group's stays, and the rail's own line. */
	distance?: Distance;
	note?: L;
	/** Trailing link for groups that point somewhere else. */
	link?: { url: string; label: L };
	/** Empty for the Airbnb group, which is a wishlist rather than a list. */
	stays: Stay[];
};

/* --------------------------------------------------------------------- data */

export const stayGroups: StayGroup[] = [
	{
		id: 'pienza',
		name: bi('Pienza', 'Pienza'),
		tagline: bi(
			'For those who want to be in the middle of it',
			'Für alle, die mittendrin sein möchten',
		),
		distance: { km: 9, minutes: 15 },
		note: bi(
			'Pienza is one of the loveliest small towns in Italy and easily one of our favourite places in Tuscany. Narrow winding lanes, beautiful piazzas, and a restaurant, café or bar on almost every corner — right for anyone who wants a bit going on around the wedding too. Add small shops to browse, local specialities, and no shortage of chances to try pecorino, salumi and wine. If your idea of a good day is a cappuccino out in the morning, an afternoon wandering the town, and an evening that ends in a wine bar, stay here.',
			'Pienza ist für uns eine der schönsten kleinen Städte Italiens und definitiv einer unserer Lieblingsorte in der Toskana. Kleine verwinkelte Gassen, wunderschöne Plätze und an beinahe jeder Ecke Restaurants, Cafés und Bars — perfekt für alle, die auch rund um die Hochzeit gerne etwas erleben möchten. Dazu kleine Geschäfte zum Bummeln, lokale Spezialitäten und jede Menge Gelegenheiten, Pecorino, Salumi und Wein zu probieren. Wenn ihr morgens einen Cappuccino trinken geht, tagsüber durch die Stadt schlendert und abends spontan noch in einer Weinbar landen möchtet, seid ihr hier genau richtig.',
		),
		stays: [
			{
				name: 'La Chiocarella',
				reserved: true,
				askUs: true,
				rooms: [{ kind: 'double', count: 3 }],
				blurb: bi(
					'Three lovely double rooms are already held here for our guests. Tell us and we will put your name on one.',
					'Drei wunderschöne Doppelzimmer sind hier bereits für unsere Gäste vorreserviert. Sagt uns Bescheid, dann tragen wir euch ein.',
				),
			},
			{
				name: 'Il Giardino Segreto',
				url: 'http://www.ilgiardinosegretopienza.it/en/',
				rooms: [{ kind: 'double' }, { kind: 'family' }, { kind: 'apartment' }],
				amenities: ['garden'],
				blurb: bi(
					'On the edge of town, with a small garden of its own.',
					'Am Stadtrand gelegen, mit einem kleinen eigenen Garten.',
				),
			},
			{
				name: 'Casa Gozzante',
				url: 'https://gozzante.com/pienza-accommodation.php',
				rooms: [{ kind: 'apartment' }],
				sleeps: 3,
				amenities: ['breakfast', 'view'],
				blurb: bi(
					'Right on the town wall, with the view and breakfast included.',
					'Ganz vorne an der Stadtmauer, mit Ausblick und Frühstück.',
				),
			},
			{
				name: 'Dimora Segreta',
				url: 'https://www.dimorasegreta.it',
				rooms: [{ kind: 'double' }],
				blurb: bi(
					'Modern, elegantly furnished doubles to a high standard.',
					'Modern und elegant eingerichtete Doppelzimmer auf hohem Standard.',
				),
			},
			{
				name: 'Agriturismo Podere San Gregorio',
				url: 'https://www.poderesangregorio.it/de/ospitalita/',
				rooms: [{ kind: 'double' }, { kind: 'family' }],
				amenities: ['breakfast'],
				blurb: bi(
					'Classic Tuscan style with breakfast — countryside, and still close enough to walk into town.',
					'Klassischer Toskana-Stil mit Frühstück — Natur und trotzdem zu Fuß in der Stadt.',
				),
			},
			{
				name: 'Hotel Corsignano',
				url: 'https://www.hotelcorsignano.it/en/',
				rooms: [{ kind: 'room' }],
				blurb: bi(
					'A small, fine hotel right in Pienza.',
					'Ein kleines, feines Hotel mitten in Pienza.',
				),
			},
		],
	},

	{
		id: 'monticchiello',
		name: bi('Monticchiello', 'Monticchiello'),
		tagline: bi('Small, authentic and a little quieter', 'Klein, authentisch und etwas ruhiger'),
		distance: { km: 1, minutes: 3 },
		note: bi(
			'Monticchiello is our other favourite village in the Val d’Orcia. The same beautiful lanes and old stone houses, exactly the Tuscany you picture — only quieter, smaller and far less touristy, a walled medieval village. You will not eat badly for it: there are several genuinely good restaurants, one of them Michelin-listed, and a few small cafés for breakfast, cappuccino and the obligatory espresso. Right for anyone who wants village life and good food without the bustle.',
			'Monticchiello ist unser zweiter kleiner Lieblingsort im Val d’Orcia. Auch hier erwarten euch wunderschöne Gassen, alte Steinhäuser und genau das Toskana-Gefühl, das man sich vorstellt — nur deutlich ruhiger, kleiner und weniger touristisch, ein malerisches Mittelalterdorf. Auf gutes Essen müsst ihr trotzdem nicht verzichten: Im Ort gibt es mehrere richtig gute Restaurants, sogar eines mit Michelin-Empfehlung, sowie ein paar kleine Cafés für Frühstück, Cappuccino und den obligatorischen Espresso. Perfekt für alle, die italienisches Dorfleben und gute Küche mögen, ansonsten aber keinen Trubel brauchen.',
		),
		stays: [
			{
				name: 'Deb’s Home',
				url: 'https://www.booking-engine.it/Scripts/group.pl?group_id=16&lang=en',
				rooms: [{ kind: 'double', count: 2 }, { kind: 'villa' }],
				sleeps: 8,
				blurb: bi(
					'Four houses in the village — Casa La Vittoria, Villa Emma, Il Torrino Suite and Villa Il Giardino del Cardinale. From a double room up to a villa for eight.',
					'Vier Häuser im Ort — Casa La Vittoria, Villa Emma, Il Torrino Suite und Villa Il Giardino del Cardinale. Vom Doppelzimmer bis zur Villa für acht.',
				),
			},
			{
				name: 'La Casa di Adelina',
				url: 'https://www.lacasadiadelina.eu/le-nostre-strutture/eleganza-nel-cuore-di-monticchiello-la-casa-di-adelina/',
				rooms: [{ kind: 'double', count: 4 }],
				blurb: bi(
					'An elegant little B&B in the heart of the village, with four doubles.',
					'Ein elegantes kleines B&B mitten im Ort, mit vier Doppelzimmern.',
				),
			},
			{
				name: 'Agriturismo Casalpiano',
				url: 'https://casalpiano.com/en/',
				distance: { minutes: 5 },
				rooms: [{ kind: 'double' }],
				amenities: ['breakfast'],
				blurb: bi(
					'Handsome double rooms with breakfast.',
					'Schöne Doppelzimmer inklusive Frühstück.',
				),
			},
			{
				name: 'Affittacamere Maria Gabriella',
				url: 'https://booking.ireservation.it/it/toscana/affittacamere-maria-gabriella-monticchiello/23959',
				distance: { minutes: 3 },
				rooms: [{ kind: 'double' }],
				sleeps: 3,
				amenities: ['garden', 'breakfast'],
				blurb: bi(
					'Quiet, good rooms and a big garden — breakfast included.',
					'Ruhe, schöne Zimmer und ein großer Garten — mit Frühstück.',
				),
			},
			{
				name: 'Appartamenti Le Maribelle',
				url: 'https://www.lemaribelle.it',
				distance: { minutes: 5 },
				rooms: [{ kind: 'apartment', count: 2 }],
				sleeps: 5,
				amenities: ['kitchen'],
				blurb: bi(
					'Two apartments with their own kitchen, each sleeping up to five.',
					'Zwei Ferienwohnungen mit eigener Küche, jeweils für bis zu fünf Personen.',
				),
			},
			{
				name: 'Casa Lizzi',
				url: 'https://www.booking.com/hotel/it/a-casa-di-lizzy-b-amp-b.html',
				distance: { minutes: 5 },
				rooms: [{ kind: 'family', count: 2 }],
				blurb: bi('Rustic and quiet, two family rooms.', 'Rustikal und ruhig, zwei Familienzimmer.'),
			},
			{
				name: 'La Casa nel Borgo',
				url: 'https://www.lacasanelborgo-toscana.it/I/Appartamenti',
				distance: { minutes: 5 },
				rooms: [{ kind: 'apartment' }],
				amenities: ['kitchen'],
				blurb: bi(
					'Modern apartments with a kitchen, for couples and families alike.',
					'Moderne Ferienwohnungen mit Küche, für Paare wie für Familien.',
				),
			},
			{
				name: 'Casa Bonari',
				url: 'https://www.casabonari.it/en/indoor/',
				distance: { minutes: 2 },
				rooms: [{ kind: 'wholeHouse' }],
				sleeps: 6,
				amenities: ['kitchen'],
				blurb: bi(
					'The whole house to yourselves — typically Tuscan rooms, a kitchen, and six beds in all.',
					'Das ganze Haus für euch, mit typisch toskanischen Zimmern, Küche und insgesamt sechs Betten.',
				),
			},
		],
	},

	{
		id: 'agriturismi',
		name: bi('Agriturismi around the villa', 'Agriturismi rund um die Villa'),
		tagline: bi(
			'For quiet, nature and the real Tuscany',
			'Für Ruhe, Natur und echtes Toskana-Gefühl',
		),
		note: bi(
			'If you do not need restaurants at the door or a town around you, and would rather switch off and look at the landscape, take one of the agriturismi nearby. We have picked out a few we like, spread around Villa Apparita and towards Pienza and Monticchiello. You wake up in the middle of the countryside, with vineyards, olive groves and the hills of the Val d’Orcia in front of you. And do not be put off by the word: agriturismo translates as farm, but in Italy it mostly means the place grows some of what it serves — its own olive oil at breakfast, say.',
			'Wenn ihr weder Restaurants direkt vor der Tür noch ein Städtchen um euch herum braucht, sondern lieber einfach abschalten und die Landschaft genießen möchtet, empfehlen wir euch eines der vielen Agriturismi in der Umgebung. Wir haben einige schöne herausgesucht, die rund um die Villa Apparita sowie in Richtung Pienza und Monticchiello liegen. Hier wacht ihr mitten in der Natur auf, mit Weinbergen, Olivenhainen und den Hügeln des Val d’Orcia direkt vor der Tür. Und bitte nicht falsch verstehen: Agriturismo wird zwar mit Bauernhof übersetzt, bedeutet in Italien aber vor allem, dass die Unterkunft eigene Produkte anbietet oder im Frühstück verwendet — zum Beispiel das eigene Olivenöl.',
		),
		link: {
			url: 'https://www.agriturismo.it/',
			label: bi(
				'An even bigger selection of agriturismi',
				'Eine noch größere Auswahl an Agriturismi',
			),
		},
		stays: [
			{
				name: 'Agriturismo Campo alla Piana',
				url: 'https://www.campoallapiana.com',
				email: 'feldallapiana@gmail.com',
				phone: '+39 338 159 2187',
				distance: { minutes: 1 },
				blurb: bi(
					'Nothing but countryside, and rooms done up with real care. Booking goes direct, by email or phone.',
					'Natur pur und mit Liebe hergerichtete Zimmer. Gebucht wird direkt per Mail oder Telefon.',
				),
			},
			{
				name: 'Agriturismo La Casellina',
				url: 'https://www.agriturismolacasellina.it/en/home-english/',
				distance: { minutes: 5 },
				rooms: [{ kind: 'double' }, { kind: 'family' }],
				amenities: ['pool', 'breakfast', 'kitchen'],
				blurb: bi(
					'Lovely doubles with breakfast and a pool; the family rooms come with their own kitchen.',
					'Sehr schöne Doppelzimmer mit Frühstück und Pool; die Familienzimmer haben eine eigene Küche.',
				),
			},
			{
				name: 'Agriturismo Marinello',
				url: 'https://www.agriturismomarinello.it/it',
				distance: { minutes: 9 },
				rooms: [{ kind: 'double' }, { kind: 'family' }],
				amenities: ['pool', 'restaurant'],
				blurb: bi(
					'A pool and a restaurant of its own, doubles and family rooms.',
					'Mit Pool und eigenem Restaurant, Doppel- und Familienzimmer.',
				),
			},
			{
				name: 'Le Sorbelle d’Orcia',
				url: 'https://www.lesorbelle.it/en/home-en/',
				distance: { minutes: 11 },
				rooms: [{ kind: 'double' }, { kind: 'family' }],
				blurb: bi(
					'Doubles and family rooms, quietly set above the Val d’Orcia.',
					'Doppel- und Familienzimmer, ruhig gelegen über dem Val d’Orcia.',
				),
			},
			{
				name: 'Posarelli Villas',
				url: 'https://www.posarellivillas.de/italien/toskana/monticchiello/1611',
				distance: { minutes: 8 },
				rooms: [{ kind: 'apartment', count: 3 }],
				amenities: ['pool'],
				blurb: bi(
					'Three self-contained apartments with a pool, in the classic Tuscan style.',
					'Drei eigene Ferienwohnungen mit Pool, im klassischen toskanischen Stil.',
				),
			},
			{
				name: 'Fonte Senesi Country House',
				url: 'https://www.fontesenesi.com',
				distance: { minutes: 7 },
				rooms: [{ kind: 'wholeHouse' }],
				sleeps: 12,
				amenities: ['pool'],
				caveat: bi('Minimum stay: one week', 'Mindestaufenthalt: eine Woche'),
				blurb: bi(
					'The whole villa for up to twelve, with a pool — the one to take if a group of you travels together.',
					'Die ganze Villa für bis zu zwölf Personen, mit Pool — das Richtige, wenn ihr als Gruppe reist.',
				),
			},
			{
				name: 'Agriturismo Lunadoro',
				url: 'https://www.agriturismolunadoro.it/GB/Rooms',
				distance: { minutes: 6 },
				rooms: [{ kind: 'double' }, { kind: 'family' }],
				amenities: ['pool', 'breakfast', 'kitchen'],
				blurb: bi(
					'Classic Tuscan, good rooms, a pool and breakfast; the family rooms have a kitchen.',
					'Klassisch toskanisch, schöne Zimmer, Pool und Frühstück; die Familienzimmer haben eine Küche.',
				),
			},
			{
				name: 'Agriturismo Palazzi del Papa',
				url: 'https://www.palazzidelpapa.it/de/',
				distance: { minutes: 14 },
				rooms: [{ kind: 'apartment', count: 5 }],
				amenities: ['pool', 'kitchen', 'animals'],
				blurb: bi(
					'Five apartments with kitchens, done in a thoroughly classic Tuscan style, plus a pool and animals. Breakfast can be added.',
					'Fünf Ferienwohnungen mit Küche in ganz klassischem Toskana-Stil, dazu Pool und Tiere. Frühstück lässt sich dazubuchen.',
				),
			},
			{
				name: 'Podere Spedalone',
				url: 'https://poderespedalone.it/home/?lang=en',
				distance: { minutes: 17 },
				rooms: [{ kind: 'room', count: 16 }, { kind: 'villa' }],
				amenities: ['pool', 'breakfast', 'restaurant'],
				blurb: bi(
					'Sixteen rooms plus a villa, with breakfast, a restaurant and a pool. The largest place on this list.',
					'Sechzehn Zimmer und dazu eine Villa, mit Frühstück, Restaurant und Pool. Das größte Haus auf dieser Liste.',
				),
			},
			{
				name: 'Agriturismo Barbi',
				url: 'http://www.agriturismobarbi.it/agriturismoing.html',
				distance: { minutes: 2 },
				rooms: [{ kind: 'double', count: 4 }],
				amenities: ['kitchen', 'selfCatering'],
				blurb: bi(
					'Four doubles, self-catering with a kitchen — kept very simple.',
					'Vier Doppelzimmer, Selbstverpflegung mit Küche — sehr einfach gehalten.',
				),
			},
			{
				name: 'Valdorcia Belvedere',
				url: 'https://www.valdorciabelvedere.it/en/bed-and-breakfast.php',
				distance: { minutes: 10 },
				rooms: [{ kind: 'double' }, { kind: 'family' }],
				amenities: ['breakfast'],
				blurb: bi(
					'Small, simple and quiet, with breakfast.',
					'Klein, einfach und ruhig, mit Frühstück.',
				),
			},
		],
	},

	{
		id: 'airbnb',
		name: bi('Airbnb', 'Airbnb'),
		tagline: bi('A wishlist we put together', 'Eine Wunschliste von uns'),
		note: bi(
			'We have also put together a small Airbnb wishlist of places we like near Villa Apparita. Most are in Monticchiello, with two more in San Quirico — another small, lovely Tuscan village. Have a look and see whether anything suits.',
			'Außerdem haben wir eine kleine Airbnb-Wunschliste angelegt und ein paar schöne Unterkünfte in der Nähe der Villa Apparita herausgesucht. Die meisten liegen in Monticchiello, zwei weitere in San Quirico — ebenfalls ein kleines, süßes Toskana-Dorf. Schaut gerne mal rein, ob etwas Passendes dabei ist.',
		),
		link: {
			url: 'https://www.airbnb.com/l/yf0MJl8Y',
			label: bi('Open the wishlist', 'Zur Wunschliste'),
		},
		stays: [],
	},

	{
		id: 'special',
		name: bi('Something special', 'Etwas Besonderes'),
		tagline: bi(
			'For anyone who fancies a little luxury',
			'Für alle, die sich ein bisschen Luxus gönnen möchten',
		),
		note: bi(
			'If you would like a bit more comfort, quiet and looking-after while you are here, we found two special addresses.',
			'Wenn ihr euch während eures Aufenthalts etwas mehr Komfort, Ruhe und Verwöhnprogramm gönnen möchtet, haben wir noch zwei besondere Adressen für euch.',
		),
		stays: [
			{
				name: 'L’Olmo',
				url: 'https://www.olmopienza.it/en/',
				distance: { minutes: 1 },
				rooms: [{ kind: 'double', count: 6 }, { kind: 'family' }],
				amenities: ['pool', 'walkable'],
				blurb: bi(
					'Within walking distance of the villa, and thoroughly luxurious, with a pool.',
					'Fußläufig zur Villa und ausgesprochen luxuriös, mit Pool.',
				),
			},
			{
				name: 'Tenuta Santo Pietro',
				url: 'https://tenutasantopietro.com',
				distance: { minutes: 18 },
				rooms: [{ kind: 'double' }, { kind: 'family' }],
				amenities: ['pool', 'breakfast', 'restaurant'],
				blurb: bi(
					'A pool, breakfast and a restaurant of its own.',
					'Pool, Frühstück und ein eigenes Restaurant.',
				),
			},
		],
	},
];

/* --------------------------------------------------------------- formatters */

export function distanceLabel(d: Distance, fromVilla = false): L {
	const unit =
		d.mode === 'foot'
			? bi(`${d.minutes} min on foot`, `${d.minutes} Min. zu Fuß`)
			: bi(`${d.minutes} min by car`, `${d.minutes} Min. mit dem Auto`);
	const km = d.km ? `${d.km} km · ` : '';
	const tail = fromVilla ? bi(' from the villa', ' von der Villa') : bi('', '');
	return bi(km + unit.en + tail.en, km + unit.de + tail.de);
}

export function roomsLabel(r: RoomSpec): L {
	const many = (r.count ?? 1) > 1;
	const l = many ? roomLabel[r.kind].many : roomLabel[r.kind].one;
	const n = many ? `${r.count} ` : '';
	return bi(n + l.en, n + l.de);
}

/**
 * One joined meta line per stay. Deliberately a single `L` rather than a row
 * of separate `<Bi>` elements — `Bi` renders both languages, so five fields
 * would cost ten spans per listing instead of two.
 */
export function metaLine(s: Stay): L {
	const parts: L[] = [];
	// Only a stay's own distance — the group's is already on the rail above,
	// and repeating it on all six Pienza rows just pads the line.
	if (s.distance) parts.push(distanceLabel(s.distance));
	for (const r of s.rooms ?? []) parts.push(roomsLabel(r));
	if (s.sleeps) parts.push(bi(`sleeps ${s.sleeps}`, `für ${s.sleeps} Personen`));
	for (const a of s.amenities ?? []) parts.push(amenityLabel[a]);
	const join = (k: keyof L) => parts.map((p) => p[k]).join(' · ');
	return bi(join('en'), join('de'));
}
